### PR TITLE
do not close system files

### PR DESCRIPTION
**Pull request by rainers**
As I never tried to build the library myself, it would be good if you could provide a build of snn.lib for testing.

### CODE REVIEW

**Comment by look-at-me** [comment]
@WalterBright Output for DMD still not displaying correctly for latest release.

**Comment by rainers** [comment]
AFAICT snn.lib was not updated in the dmd distribution.

**Comment by RazvanN7** [comment]
ping @WalterBright Updating the snn.lib will close issue 1550: https://issues.dlang.org/show_bug.cgi?id=1550

**Comment by WalterBright** [comment]
Where do I put the new snn.lib?

**Comment by RazvanN7** [comment]
This is where the release build program downloads it from:  http://ftp.digitalmars.com/snn.lib

**Comment by WalterBright** [comment]
I think the file there is correct now.

**Pull request merged**
